/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssistantToolsFileSearchFileSearch : Overrides for the file search tool.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantToolsFileSearchFileSearch {
    /// The maximum number of results the file search tool should output. The default is 20 for gpt-4* models and 5 for gpt-3.5-turbo. This number should be between 1 and 50 inclusive.  Note that the file search tool may output fewer than `max_num_results` results. See the [file search tool documentation](/docs/assistants/tools/file-search/number-of-chunks-returned) for more information. 
    #[serde(rename = "max_num_results", skip_serializing_if = "Option::is_none")]
    pub max_num_results: Option<i32>,
}

impl AssistantToolsFileSearchFileSearch {
    /// Overrides for the file search tool.
    pub fn new() -> AssistantToolsFileSearchFileSearch {
        AssistantToolsFileSearchFileSearch {
            max_num_results: None,
        }
    }
}

