/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FinetuneChatRequestInput : The per-line training example of a fine-tuning input file for chat models
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinetuneChatRequestInput {
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<models::FinetuneChatRequestInputMessagesInner>>,
    /// A list of tools the model may generate JSON inputs for.
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<models::ChatCompletionTool>>,
    /// Whether to enable [parallel function calling](/docs/guides/function-calling/parallel-function-calling) during tool use.
    #[serde(rename = "parallel_tool_calls", skip_serializing_if = "Option::is_none")]
    pub parallel_tool_calls: Option<bool>,
    /// A list of functions the model may generate JSON inputs for.
    #[serde(rename = "functions", skip_serializing_if = "Option::is_none")]
    pub functions: Option<Vec<models::ChatCompletionFunctions>>,
}

impl FinetuneChatRequestInput {
    /// The per-line training example of a fine-tuning input file for chat models
    pub fn new() -> FinetuneChatRequestInput {
        FinetuneChatRequestInput {
            messages: None,
            tools: None,
            parallel_tool_calls: None,
            functions: None,
        }
    }
}

